---
title: "Résultats générés automatiquement"
author: "Lino"
date: "22/04/2020"
output:
  html_document:
  fig_width: 16 
  fig_height: 10 
params:
  beta: 0.98
  gamma: 0.5
  r: 0.03
  Nmoments: 3
  parameters_estimation: list()
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, include=FALSE}
library(tablelight)
r <- params$r
beta <- params$beta
gamma <- params$gamma

model <- readRDS("modele.rds")
population <- readRDS("tempfile.rds")
data <- readRDS("data.rds")
EP_2015 <- data[['EP_2015']]
EP_2018 <- data[['EP_2018']]
EP_lon <- data[['EP_lon']]

list2env(params$parameters_estimation, envir = .GlobalEnv)
source("liste_moments.R")

if (!is.null(select_moments)){
  number_moments <- length(1:number_moments[1:number_moments %in% select_moments])
} else{
  number_moments <- number_moments
}
```

# Prolégomènes

Valeur des paramètres:

* r: `r r`
* gamma: `r gamma`
* beta: `r beta`
* Nmoments: `r number_moments`

Moments sélectionnés:

```{r}

df_moment <- wealthyR::loss_function(
  prediction_function = wealthyR:::model_capitulation,
  select_moments = select_moments,
  theta = c('beta' = beta,
            'gamma' = gamma,
            "r" = r),
  EP_2015 = EP_2015,
  EP_lon = EP_lon,
  EP_2018 = EP_2018,
  data_microsimulated = population,
  N_moments = number_moments,
  scale = scale_wealth,
  Hgiven_var = "hg",
  Hreceived_var = "hr",
  return_moment = TRUE
)

labelized_moments <-  label_moments(
    N_moments = number_moments,
    scale = scale_wealth,
    select_moments = select_moments
  )


knitr::kable(
  merge(labelized_moments, df_moment, by = "Nmoment")
             )
```


Modèle d'héritage:

```{r}
tf <- tempfile(fileext = ".html")
writeLines(light_table(
  model, type = "html"
), tf)
htmltools::includeHTML(tf)
```

# Estimation du modèle

```{r, echo = TRUE}
data_prediction_augm2 <- capitulation::life_cycle_model(
  population,
  wealthvar_survey = "K_observed",
  r = r,
  beta = beta,
  gamma = gamma,
  observation_year = 2009,
  income_var = "revenu",
  Hgiven_var = "hg",
  Hreceived_var = "hr",
  return_last = FALSE,
  get_capital_income = TRUE)
```

# Résultats

```{r}
capitulation::plot_K_age(data_prediction_augm2)
```

```{r}
capitulation::plot_rK_age(data_prediction_augm2)
```

```{r}
capitulation::plot_gini(data_prediction_augm2,
                        vars = c("revenu", "wealth", "Y"))
```


```{r}
LC1 <- ineq::Lc(data_prediction_augm2[annee==2020 & wealth>0]$wealth, plot = FALSE)
LC2 <- ineq::Lc(data_prediction_augm2[annee==2020 & wealth>0]$revenu, plot = FALSE)
df <- data.frame(p1 = LC1$p,
                 wealth = LC1$L,
                 uniform = LC1$p, 
                 y = LC2$L)
df <- data.table::data.table(reshape2::melt(df, id.vars = "p1"))

df[, 'lab' := "Pure equality"]
df[variable == "wealth", lab := "Wealth"]
df[variable == "y", lab := "Labor income"]


p <- ggplot2::ggplot(df) +
  ggplot2::geom_line(ggplot2::aes(x = p1, y = value, color = lab))+
  ggplot2::theme(legend.position="bottom") +
  ggplot2::scale_color_viridis_d() +
  ggplot2::labs(x = "", y = "", color = "") +
  ggplot2::theme(text = ggplot2::element_text(size=24),
                 axis.title = ggplot2::element_text(size=20,face="bold"))

p
```


# Graphs pour évaluer la qualité du fit

Se référer au tableau pour les moments inclus dans l'analyse. 

* Moments 1 et 3:

```{r}
wealthyR::plot_moment_pic(EP_2015 = EP_2015,
                EP_2018 = EP_2018,
                simulations = simulations,
                scale = "log")
```


* Moment 2:

```{r}
wealthyR::plot_moment_dK(
  EP_lon = EP_lon, simulations = simulations,
  scale = "level"
)
```

* Moments sur la distribution par âge du patrimoine (number ???):

```{r}
wealthyR::plot_moment_age_multiple(
  EP_2015 = EP_2015,
  EP_2018 = EP_2018,
  simulations = simulations,
  scale = "level"
)
```
