---
title: "Résultats générés automatiquement"
author: "Lino"
date: "22/04/2020"
output:
  html_document:
  fig_width: 16 
  fig_height: 10 
params:
  beta: 0.98
  gamma: 0.5
  r: 0.03
  N_moments: 6
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, include=FALSE}
library(tablelight)
r <- params$r
beta <- params$beta
gamma <- params$gamma

population <- readRDS("tempfile.rds")
data <- readRDS("data.rds")
EP_2015 <- data[['EP_2015']]
EP_2018 <- data[['EP_2018']]
EP_lon <- data[['EP_lon']]
```

# Prolégomènes

Valeur des paramètres:

* r: `r r`
* gamma: `r gamma`
* beta: `r beta`
* Number of moments: `r N_moments`


# Estimation du modèle

```{r, echo = TRUE}
data_prediction_augm2 <- capitulation::life_cycle_model(
  population,
  wealthvar_survey = "K_observed",
  r = r,
  beta = beta,
  gamma = gamma,
  observation_year = 2009,
  income_var = "y_indiv",
  return_last = FALSE,
  get_capital_income = TRUE)
```

# Résultats

```{r}
capitulation::plot_K_age(data_prediction_augm2)
```

```{r}
capitulation::plot_rK_age(data_prediction_augm2)
```

```{r}
capitulation::plot_gini(data_prediction_augm2,
                        vars = c("y_indiv", "wealth", "Y"))
```


```{r}
LC1 <- ineq::Lc(data_prediction_augm2[annee==2020 & wealth>0]$wealth, plot = FALSE)
LC2 <- ineq::Lc(data_prediction_augm2[annee==2020 & wealth>0]$y_indiv, plot = FALSE)
df <- data.frame(p1 = LC1$p,
                 wealth = LC1$L,
                 uniform = LC1$p, 
                 y = LC2$L)
df <- data.table::data.table(reshape2::melt(df, id.vars = "p1"))

df[, 'lab' := "Pure equality"]
df[variable == "wealth", lab := "Wealth"]
df[variable == "y", lab := "Labor income"]


p <- ggplot2::ggplot(df) +
  ggplot2::geom_line(ggplot2::aes(x = p1, y = value, color = lab))+
  ggplot2::theme(legend.position="bottom") +
  ggplot2::scale_color_viridis_d() +
  ggplot2::labs(x = "", y = "", color = "") +
  ggplot2::theme(text = ggplot2::element_text(size=24),
                 axis.title = ggplot2::element_text(size=20,face="bold"))

p
```


