---
title: "Comparaison résultats avec/sans incertitude"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>", echo = FALSE, warning  = FALSE, message = FALSE)
library(targets)
source("functions.R", encoding = "UTF-8")
```

```{r}
tar_load(output)
tar_load(output_selection)
tar_load(output_uncertainty)
tar_load(output_uncertainty_selection)
tar_load(test_moments)
tar_load(test_moments_uncertainty)
tar_load(test_moments_selection)
tar_load(test_moments_uncertainty_selection)
```


```{r}
p1 = plot_moment_age_wide(test_moments_selection)
p1_uncertainty = plot_moment_age_wide(test_moments_uncertainty_selection)
```

```{r}
theta_hat <- output_selection$estimates$theta_hat
theta_hat_se <- output_selection$estimates$se_theta_hat
print(sprintf("Modèle sans incertitude, beta: %s (%s)",
              format(theta_hat, digits = 4),
              format(theta_hat_se, digits = 2)))
```

```{r}
theta_hat <- output_uncertainty_selection$estimates$theta_hat
theta_hat_se <- output_uncertainty_selection$estimates$se_theta_hat
print(sprintf("Modèle avec incertitude, beta: %s (%s)",
              format(theta_hat, digits = 4),
              format(theta_hat_se, digits = 2)))
```

## Moment 1

Modèle sans incertitude:

```{r}
output_selection$moments$moment_optimum[1:13]
```

Modèle avec incertitude:

```{r}
output_uncertainty_selection$moments$moment_optimum[1:13]
```

Modèle sans incertitude:

```{r}
p1[[1]]
```

Modèle avec incertitude:

```{r}
p1_uncertainty[[1]]
```


## Moment 2

Modèle sans incertitude: 

```{r}
output_selection$moments$moment_optimum[14:21]
```

Modèle avec incertitude: 

```{r}
output_uncertainty_selection$moments$moment_optimum[14:21]
```

Modèle sans incertitude: 

```{r}
p1[[2]]
```

Modèle avec incertitude: 


```{r}
p1_uncertainty[[2]]
```

