---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
inheritance_model <- readRDS("../modele.rds")


population <- readRDS(file = "../tempfile.rds")


path_data <- "../.."
source("../functions.R")

data <- construct_EP(path_data)


EP_2015 <- data[['EP_2015']]
EP_2018 <- data[['EP_2018']]
EP_lon <- data[['EP_lon']]


output_piste1 <- readRDS("output_piste1.rds")
output_piste2 <- readRDS("output_piste2.rds")
output_log <- readRDS("output_model_scale_log.rds")

beta_piste1  <- output_piste1$estimates$theta_hat['beta']
gamma_piste1 <- output_piste1$estimates$theta_hat['gamma']
beta_piste2  <- output_piste2$estimates$theta_hat['beta']
gamma_piste2 <- output_piste2$estimates$theta_hat['gamma']
r <- 0.03
```

```{r, results="asis"}
cat(tablelight::light_table(output_piste1, type = "html", covariate.labels = c("$\\beta$", "$\\gamma$"),
                                              dep.var.labels = "\\textsc{Estimates}", column.labels = NULL,
                            title = "Modèle 1: arcsinh avec scale_model = log"))

cat(tablelight::light_table(output_piste2, type = "html", covariate.labels = c("$\\beta$", "$\\gamma$"),
                                              dep.var.labels = "\\textsc{Estimates}", column.labels = NULL,
                            title = "Modèle 2: arcsinh avec scale_model = level"))

cat(tablelight::light_table(output_log, type = "html", covariate.labels = c("$\\beta$", "$\\gamma$"),
                                              dep.var.labels = "\\textsc{Estimates}", column.labels = NULL,
                            title = "Modèle 3: moment1 in level avec scale_model = level"))

```

# Profil par âge

```{r}
simulations <- capitulation::life_cycle_model(
  population,
  wealthvar_survey = "K_observed",
  r = r,
  beta = beta_piste2,
  gamma = gamma_piste2,
  observation_year = 2009,
  income_var = "revenu",
  Hgiven_var = "hg",
  Hreceived_var = "hr",
  # return_last = TRUE,
  get_capital_income = TRUE,
  scale_model = "level",
  additional_vars = c("tr_age_2015","sexe","findet"))
simulations <- simulations[age > findet]

```

```{r}
capitulation::plot_K_age(simulations, xlims = c(30,75), method = "median")
```

```{r}
capitulation::plot_rK_age(simulations, xlims = c(30,75))
```

# Moments

```{r}
clean_data <- function(data, sex_var = "sexe",
                       diploma_var = "findet",
                       labor_income_var = "revenu",
                       total_income_var = "Y",
                       year = 2015){
  
  
  data[, c('SEXE') := data.table::fifelse(get(sex_var)==1,
                                          'Male',
                                          'Female')]
  data[, c('tr_diplome') := cut(get(diploma_var), breaks = c(min(get(diploma_var)), 16,18,21,25, max(get(diploma_var))), include.lowest = TRUE)]
  
  if (year != 2015) return(data)  
  
  data[, c('decile_w') := cut(get(labor_income_var),
                              quantile(get(labor_income_var),
                                       probs= 0:10/10) + seq_along(0:10)*.Machine$double.eps,
                              labels = 1:10, include.lowest = TRUE
  )]
  data[, c('decile_y') := cut(get(total_income_var),
                              quantile(get(total_income_var),
                                       probs= 0:10/10)  + seq_along(0:10)*.Machine$double.eps,
                              labels = 1:10, include.lowest = TRUE
  )]
  
  return(data)
  
}

clean_data(simulations)

EP_2015[,'y' := get('w') + r*get('PATFISOM')]
EP_2015[, 'annee' := 2015]
clean_data(EP_2015, sex_var = "SEXE", labor_income_var = "w", diploma_var = "AGFINETU",
           total_income_var = "y")

EP_2018[, 'annee' := 2018]
clean_data(EP_2018, sex_var = "SEXE", year = 2018, diploma_var = "AGFINETU")


EP_lon[,'y' := get('w_2015') + r*get('PATFISOM_2015')]
EP_lon <- merge(EP_lon, EP_2015[,.SD,.SDcols = c("IDENTIND14","tr_diplome", "decile_w", "decile_y")],
                by = c("IDENTIND14"))
EP_lon[, c('SEXE') := data.table::fifelse(get('SEXE')==1,
                                          'Homme',
                                          'Femme')]

```

```{r}
library(ggplot2)
tempdf = output_piste2$moments$moment_optimum[get("Nmoment") <62]
moments = data.table::melt(tempdf[, .SD, .SDcols = c("Nmoment", "moment_simulations", "moment_data")],
                 id.vars = c("Nmoment"))
moments[,'age' := get("Nmoment")+19]
ggplot2::ggplot(moments) +
    ggplot2::geom_bar(ggplot2::aes(x = age, y = value,
                                   fill = variable), position = "dodge",
                      stat='identity', width=.5) +
    ggplot2::scale_color_viridis_d() +
    ggplot2::scale_fill_viridis_d() +
    ggplot2::labs(x = "Age", y = "Median wealth") +
    ggplot2::theme(legend.position = "top") +
    scale_fill_manual(values = c('moment_simulations' = 'black', 
                                 'moment_data' = 'royalblue')) + theme_bw() +
    theme(legend.position = "top")
```


```{r}
tempdf = output_piste2$moments$moment_optimum[get("Nmoment") >+62]
moments = data.table::melt(tempdf[, .SD, .SDcols = c("Nmoment", "moment_simulations", "moment_data")],
                 id.vars = c("Nmoment"))
moments[,'age' := seq(30, length.out = .N, by = 5), by = variable]

ggplot2::ggplot(moments) + geom_line(aes(x = age, y = value, color = variable)) +
  geom_point(aes(x = age, y = value, color = variable, shape = variable)) +
  geom_hline(yintercept = 0, color = "red") +
  scale_color_manual(values = c('moment_simulations' = 'black', 
                                  'moment_data' = 'royalblue')) + theme_bw() +
  theme(legend.position = "bottom")
```


# Taux d'endettement

```{r}
simulations[,'endet' := get("wealth") < 0]
df_endet <- simulations[annee == 2015, .('taux_endet' = mean(endet)), by = "age"]
df_endet[,'source' := 'microsimulation']
df_endet2 <- data.table::copy(EP_2015)
data.table::setnames(df_endet2, old = "AGE", new = "age")
df_endet2[,'endet' := get("PATRI_NET") < 0]
df_endet2 <- df_endet2[, .('taux_endet' = mean(endet)), by = "age"]
df_endet2[,'source' := 'survey']
df_endet <- data.table::rbindlist(list(df_endet, df_endet2))

ggplot(simulations[, .('taux_endet' = mean(endet)), by = "annee"]) +
  geom_line(aes(x = annee, y = taux_endet)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  xlim(2009,2040) + labs(y = "Part individus endettés")


ggplot(df_endet) +
  geom_line(aes(x = age, y = taux_endet, color = source)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  labs(y = "Part individus endettés (en 2015)")

```


