FROM git-registry.stable.innovation.insee.eu/innovation/rstudio
MAINTAINER Lino Galiana <lino.galiana@insee.fr>

COPY install.sh /install.sh

RUN chmod +x /install.sh && /install.sh


VOLUME ["/home"]